# Generated by Django 4.2.4 on 2023-10-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_permissions_can_checkout_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvite',
            name='message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
