# Generated by Django 4.2.4 on 2023-11-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_can_edit_user_permission_permissions_can_edit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='can_edit_user',
            new_name='can_edit_user_permissions',
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_delete_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_edit_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_finish_project',
            field=models.BooleanField(default=False),
        ),
    ]
